image: node:8

cache:
  untracked: true
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

stages:
  # - Build
  - Tests
  - Package

# "Build Docker Container":
#   stage: Build
#   image: docker:git
#   services:
#     - docker:dind
#   before_script:
#     - ":"
#   script:
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#     - docker build -t registry.gitlab.com/renyard/validity:${CI_JOB_ID}_${CI_COMMIT_SHA} ./
#     - docker push registry.gitlab.com/renyard/validity:${CI_JOB_ID}_${CI_COMMIT_SHA}

"Unit Tests":
  stage: Tests
  before_script:
    - npm install
  script:
    - npm test
  coverage: '/All files\s*\|\s*([0-9.]+)/'

"Integration Tests":
  stage: Tests
  image: ubuntu:18.04
  before_script:
    - apt update -y && apt install -y firefox nodejs npm
    - npm install
  script:
    - npm run test:integration

# "Integration Tests":
#   stage: Tests
#   image: docker:git
#   services:
#     - docker:dind
#   before_script:
#     - apk add --no-cache py-pip
#     - pip install docker-compose
#   script:
#     - docker-compose up --build --abort-on-container-exit --exit-code-from validity


# "Mutation Tests":
#   stage: Tests
#   before_script:
#     - npm install
#   script:
#     - npm run test:mutation

"Tag Release":
  stage: Package
  only:
    - master
  script:
    - VER=$(node -p -e "require('./package.json').version") git rev-parse v$VER || git tag v$VER

"Package":
  stage: Package
  before_script:
    - npm install
  script:
    - npm run package
  artifacts:
    paths:
      - dist/validity*.zip
