image: node:8

cache:
  untracked: true
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

stages:
  - Tests
  - Tag
  - Package

before_script:
  - npm install

"Unit Tests":
  stage: Tests
  script:
    - npm test

"Integration Tests":
  stage: Tests
  script:
    - ":"

"Tag Release":
  stage: Tag
  only:
    - master
  script:
    - VER=$(node -p -e "require('./package.json').version") git rev-parse v$VER || git tag v$VER

"Package":
  stage: Package
  script:
    - npm install
    - npm run package
  artifacts:
    paths:
      - dist/validity*.zip
