image: node:8

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/

stages:
  - install
  - tests
  - tag

"Install":
  stage: install
  script:
  - npm install

"Unit Tests":
  stage: tests
  dependencies:
    - "Install"
  script:
    - npm test

"Integration Tests":
  stage: tests
  dependencies:
    - "Install"
  script:
    - ":"

"Tag Release":
  stage: tag
  dependencies:
    - "Unit Tests"
    - "Integration Tests"
  only:
    - master
  script:
    - VER=$(node -p -e "require('./package.json').version") git rev-parse v$VER || git tag v$VER
