language: node_js
sudo: true
dist: trusty
addons:
  apt:
    packages:
      - google-chrome-stable
  code_climate:
    repo_token:
      secure: Qg7aU259poF/3O8mPtYqeOe6CI2BGxFSxcjcqCrJ2ZeGc5977cbpBYqdk17QsK3XVbCjF6AglqDh+16PFTF224ygCqPsxH6yhD1tFKDqOG4sxjpshmD8wctnQIzPnjfMOiITIELCttXzzb0XiLJTPyu2zOTCQvgO4dxAp2q9OYc=
node_js:
  - stable
before_install:
  - npm install -g grunt-cli
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: npm install
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/**/lcov.info
